
import { ProductBatch, Supplier } from './types';

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: 'supp_ken_01', name: 'Nairobi Leather Artisans', country: 'Kenya', verificationStatus: 'Verified', rating: 4.8, memberSince: '2022-03-15', bio: 'A collective of skilled leatherworkers from Nairobi, specializing in traditional techniques passed down through generations. We focus on sustainable sourcing and high-quality craftsmanship.' },
  { id: 'supp_nga_01', name: 'Adire Indigo Textiles', country: 'Nigeria', verificationStatus: 'Verified', rating: 4.9, memberSince: '2021-11-01', bio: 'Experts in the ancient art of Adire indigo dyeing. Our textiles are handmade in Osogbo, a city renowned for its rich artistic heritage.' },
  { id: 'supp_vnm_01', name: 'Mekong Woven Goods', country: 'Vietnam', verificationStatus: 'Verified', rating: 4.7, memberSince: '2023-01-20', bio: 'We work with local communities in the Mekong Delta to create beautiful, eco-friendly products from natural fibers like seagrass and water hyacinth.' },
  { id: 'supp_ken_02', name: 'Maasai Beaders Collective', country: 'Kenya', verificationStatus: 'Verified', rating: 4.9, memberSince: '2022-08-10', bio: 'Preserving the intricate art of Maasai beadwork. Each piece is handcrafted by women in the Amboseli region, providing a vital source of income and cultural preservation.' },
  { id: 'supp_gha_01', name: 'Ghanaian Shea Cooperative', country: 'Ghana', verificationStatus: 'Verified', rating: 4.8, memberSince: '2020-05-30', bio: 'A women-led cooperative producing pure, unrefined Grade A shea butter and natural skincare products using traditional, sustainable methods.' },
  { id: 'supp_nga_02', name: 'Lagos Brass Casters', country: 'Nigeria', verificationStatus: 'Pending', rating: 4.6, memberSince: '2023-05-12', bio: 'Reviving the lost-wax casting technique to create modern jewelry from recycled brass. Our designs are inspired by ancient West African motifs.' },
  { id: 'supp_mar_01', name: 'Marrakech Weavers Guild', country: 'Morocco', verificationStatus: 'Verified', rating: 4.9, memberSince: '2021-09-01', bio: 'Artisans from the Atlas Mountains, weaving stunning Berber rugs and textiles with hand-spun wool and natural dyes.'},
  { id: 'supp_ind_01', name: 'Jaipur Block Printers', country: 'India', verificationStatus: 'Verified', rating: 4.8, memberSince: '2022-02-11', bio: 'Masters of traditional Rajasthani block printing. We create vibrant, handcrafted textiles for fashion and home decor.' },
  { id: 'supp_per_01', name: 'Cusco Alpaca Textiles', country: 'Peru', verificationStatus: 'Verified', rating: 5.0, memberSince: '2020-10-05', bio: 'Sourcing the finest alpaca fibers from the Andean highlands to create luxuriously soft throws, scarves, and apparel.' },
];


export const MOCK_PRODUCTS: ProductBatch[] = [
  {
    supplierId: 'supp_ken_01',
    title: 'Hand-Stitched Leather Wallet',
    category: 'Textile Accessories',
    description: 'A premium, full-grain leather wallet, hand-stitched by artisans in Nairobi. Features 6 card slots and a main bill compartment. Built to last a lifetime.',
    materials: ['Full-grain cowhide leather', 'Waxed thread'],
    specs: { 'Dimensions': '11cm x 9cm', 'Weight': '80g', 'Color': 'Tan Brown' },
    moq: 25,
    leadTimeDays: 14,
    images: ['https://images.unsplash.com/photo-1619458991960-ab2d17215263?q=80&w=2070&auto=format&fit=crop', 'https://images.unsplash.com/photo-1615437632141-196c3a1bd34a?q=80&w=2070&auto=format&fit=crop', 'https://images.unsplash.com/photo-1620625513874-4a23b5d6a36c?q=80&w=1974&auto=format&fit=crop'],
    videoUrl: 'https://example.com/video.mp4',
    productId: 'prod_001',
    id: 'batch_001',
    qtyAvailable: 150,
    unitPriceUSD: 22.50,
    status: 'available',
    mlQualityScore: 'A',
  },
  {
    supplierId: 'supp_nga_01',
    title: 'Adire Patterned Silk Scarf',
    category: 'Textile Accessories',
    description: 'Vibrant silk scarf featuring traditional Adire dyeing techniques from Nigeria. Each piece is unique, offering a bold statement of color and culture.',
    materials: ['100% Silk', 'Natural dyes'],
    specs: { 'Dimensions': '180cm x 70cm', 'Care': 'Hand wash cold' },
    moq: 50,
    leadTimeDays: 21,
    images: ['https://images.unsplash.com/photo-1596903268831-a0e2a2a1f0a0?q=80&w=1935&auto=format&fit=crop', 'https://images.unsplash.com/photo-1610424251211-2d7c5b6b1070?q=80&w=1935&auto=format&fit=crop'],
    productId: 'prod_002',
    id: 'batch_002',
    qtyAvailable: 300,
    unitPriceUSD: 15.00,
    status: 'available',
    mlQualityScore: 'A',
  },
    {
    supplierId: 'supp_mar_01',
    title: 'Moroccan Leather Pouf',
    category: 'Home Goods',
    description: 'Handmade leather pouf from Marrakech, perfect as a footstool or extra seating. Stuffed with dense cotton for firm support. Intricate embroidered detailing.',
    materials: ['Goatskin Leather', 'Silk Thread', 'Cotton Batting'],
    specs: { 'Diameter': '55cm', 'Height': '35cm', 'Color': 'Natural Tan' },
    moq: 10,
    leadTimeDays: 25,
    images: ['https://images.unsplash.com/photo-1593132223537-67230235c5a8?q=80&w=1964&auto=format&fit=crop', 'https://images.unsplash.com/photo-1593132223588-212a401c440a?q=80&w=1964&auto=format&fit=crop'],
    productId: 'prod_007',
    id: 'batch_007',
    qtyAvailable: 40,
    unitPriceUSD: 45.00,
    status: 'available',
    mlQualityScore: 'A',
  },
  {
    supplierId: 'supp_vnm_01',
    title: 'Woven Seagrass Tote Bag',
    category: 'Bags',
    description: 'Eco-friendly and stylish tote bag, handwoven from natural seagrass by skilled artisans in Vietnam. Perfect for beach trips or daily errands.',
    materials: ['Seagrass', 'Cotton lining'],
    specs: { 'Dimensions': '40cm x 30cm x 15cm', 'Strap Drop': '25cm' },
    moq: 40,
    leadTimeDays: 30,
    images: ['https://images.unsplash.com/photo-1571524953344-3dbe736b56a3?q=80&w=1974&auto=format&fit=crop', 'https://images.unsplash.com/photo-1621457190022-72124505118d?q=80&w=1932&auto=format&fit=crop'],
    productId: 'prod_003',
    id: 'batch_003',
    qtyAvailable: 80,
    unitPriceUSD: 18.75,
    status: 'verifying',
    mlQualityScore: 'B',
  },
  {
    supplierId: 'supp_ind_01',
    title: 'Hand-Blocked Print Fabric',
    category: 'Textiles',
    description: '100% cotton fabric featuring intricate floral motifs, hand-printed by artisans in Jaipur using traditional wooden blocks and natural dyes.',
    materials: ['100% Cotton', 'Vegetable Dyes'],
    specs: { 'Width': '44 inches', 'GSM': '150', 'Pattern': 'Paisley Bloom' },
    moq: 100, // in meters
    leadTimeDays: 28,
    images: ['https://images.unsplash.com/photo-1620722398431-1522497da814?q=80&w=1974&auto=format&fit=crop', 'https://images.unsplash.com/photo-1620722399139-2c13d7881ac1?q=80&w=1974&auto=format&fit=crop'],
    productId: 'prod_008',
    id: 'batch_008',
    qtyAvailable: 1000, // in meters
    unitPriceUSD: 6.50, // per meter
    status: 'available',
    mlQualityScore: 'A',
  },
  {
    supplierId: 'supp_ken_02',
    title: 'Beaded Maasai Leather Belt',
    category: 'Textile Accessories',
    description: 'Authentic Maasai belt made with genuine leather and hand-applied glass beads. Each belt tells a story through its intricate patterns and colors.',
    materials: ['Leather', 'Glass beads', 'Brass buckle'],
    specs: { 'Width': '1.5 inches', 'Sizes': 'S, M, L, XL' },
    moq: 20,
    leadTimeDays: 18,
    images: ['https://images.unsplash.com/photo-1628149298486-ff8a5a51930b?q=80&w=1964&auto=format&fit=crop', 'https://images.unsplash.com/photo-1628149298492-5954605b058a?q=80&w=1964&auto=format&fit=crop'],
    productId: 'prod_004',
    id: 'batch_004',
    qtyAvailable: 120,
    unitPriceUSD: 28.00,
    status: 'available',
    mlQualityScore: 'A',
  },
  {
    supplierId: 'supp_gha_01',
    title: 'Shea Butter & Baobab Soap',
    category: 'Natural Soaps',
    description: 'Cold-pressed natural soap bar enriched with raw shea butter and baobab oil from Ghana. Deeply moisturizing and suitable for all skin types.',
    materials: ['Shea Butter', 'Baobab Oil', 'Coconut Oil', 'Lye'],
    specs: { 'Weight': '150g', 'Scent': 'Unscented, natural' },
    moq: 100,
    leadTimeDays: 25,
    images: ['https://images.unsplash.com/photo-1600958933254-6e65b71948ba?q=80&w=1974&auto=format&fit=crop', 'https://images.unsplash.com/photo-1626332195869-aa5e4c4f39e3?q=80&w=1974&auto=format&fit=crop'],
    productId: 'prod_005',
    id: 'batch_005',
    qtyAvailable: 500,
    unitPriceUSD: 4.50,
    status: 'available',
    mlQualityScore: 'A',
  },
  {
    supplierId: 'supp_per_01',
    title: 'Baby Alpaca Wool Throw',
    category: 'Home Goods',
    description: 'Incredibly soft and warm throw blanket woven from 100% baby alpaca wool from the Peruvian Andes. Hypoallergenic and lightweight.',
    materials: ['100% Baby Alpaca Wool'],
    specs: { 'Dimensions': '130cm x 180cm', 'Weight': '500g', 'Color': 'Heather Grey' },
    moq: 15,
    leadTimeDays: 35,
    images: ['https://images.unsplash.com/photo-1620917609289-1a4a2f87f43e?q=80&w=1964&auto=format&fit=crop', 'https://images.unsplash.com/photo-1616625807424-41a4a4752c16?q=80&w=1964&auto=format&fit=crop'],
    productId: 'prod_009',
    id: 'batch_009',
    qtyAvailable: 60,
    unitPriceUSD: 75.00,
    status: 'available',
    mlQualityScore: 'A',
  },
  {
    supplierId: 'supp_nga_02',
    title: 'Recycled Brass Cast Earrings',
    category: 'Jewelry',
    description: 'Stunning earrings cast from recycled brass using ancient lost-wax techniques. Bold, geometric design inspired by West African symbolism.',
    materials: ['Recycled brass'],
    specs: { 'Length': '5cm', 'Fastening': 'Hook' },
    moq: 30,
    leadTimeDays: 20,
    images: ['https://images.unsplash.com/photo-1611652033959-8a52dc085a1e?q=80&w=1974&auto=format&fit=crop', 'https://images.unsplash.com/photo-1611652033931-489434407883?q=80&w=1974&auto=format&fit=crop'],
    productId: 'prod_006',
    id: 'batch_006',
    qtyAvailable: 75,
    unitPriceUSD: 12.00,
    status: 'verifying',
    mlQualityScore: 'C',
  },
];
